import { mkdir, writeFile } from "node:fs/promises";

const PROFILE_REPO_RAW = "https://raw.githubusercontent.com/ManavSharma2707/ManavSharma2707/main";

async function fetchText(path: string): Promise<string> {
  const response = await fetch(`${PROFILE_REPO_RAW}/${path}`);
  if (!response.ok) throw new Error(`Failed to fetch ${path}: ${response.status}`);
  return response.text();
}

interface DesignTokens {
  color: unknown;
  heatmapScale: unknown;
  light: unknown;
  font: unknown;
  motion: unknown;
  spacing: unknown;
}

async function syncMetrics(): Promise<void> {
  const json = await fetchText("assets/generated/metrics.json");
  await mkdir("public", { recursive: true });
  await writeFile("public/metrics.json", json, "utf8");
  console.log("Synced public/metrics.json from the profile repo");
}

async function syncTokens(): Promise<void> {
  const json = await fetchText("design/tokens.json");
  const tokens = JSON.parse(json) as DesignTokens;
  const body = `// Generated by scripts/sync-data.ts from the profile repo's design/tokens.json.
// Do not edit by hand, this file is overwritten on every build.

export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type Tokens = typeof tokens;
`;
  await mkdir("src/theme", { recursive: true });
  await writeFile("src/theme/tokens.ts", body, "utf8");
  console.log("Synced src/theme/tokens.ts from the profile repo");
}

async function main() {
  try {
    await Promise.all([syncMetrics(), syncTokens()]);
  } catch (error) {
    console.error("Sync failed, keeping existing local copies:", error);
    process.exitCode = 1;
  }
}

main();
